[k8s_nodes]
control-plane  ansible_host=10.0.1.181
worker-1       ansible_host=10.0.2.94
worker-2       ansible_host=10.0.1.212

[k8s_nodes:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/windek/Downloads/DeevOps_Repo/terraform/environments/dev/dev-key.pem
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i /home/windek/Downloads/DeevOps_Repo/terraform/environments/dev/dev-key.pem -o StrictHostKeyChecking=no -W %h:%p ubuntu@100.29.187.196"