apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: minibank
data:
  config.yaml: |
    server:
      port: 8000
      log_level: "INFO"
    broker:
      host: "rabbitmq.minibank.svc.cluster.local"
      port: 5672
      queue: "notifications.events"
      prefetch_count: 10
    notifications:
      email_mock_enabled: true
      sms_mock_enabled: true
