# Values for bitnami/rabbitmq
auth:
  username: "minibank_broker"
  existingPasswordSecret: "rabbitmq-credentials"

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  size: 8Gi