apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-servicemonitor
  namespace: minibank
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: minibank
    release: monitoring
spec:
  # Discovers the api-gateway-service in the minibank namespace
  selector:
    matchLabels:
      app: api-gateway
  namespaceSelector:
    matchNames:
      - minibank
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
