apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: minibank
  labels:
    app: api-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: api-gateway-sa
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: api-gateway
      containers:
      - name: api-gateway
        image: ghcr.io/co-windeksolutions/omini_bank-project/api-gateway:7f9655e #Ebuka add image path here
        ports:
        - name: http
          containerPort: 8000

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop: ["ALL"]

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

        volumeMounts:
        - name: config-volume
          mountPath: /etc/minibank/config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: api-gateway-config