apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: minibank
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: minibank
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      serviceAccountName: notification-sa

      # Multi-AZ Spread
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: notification-service

      # NOTE: No initContainers needed here because Notification has no DB/schema migrations.

      containers:
      - name: notification-service
        image: ghcr.io/co-windeksolutions/omini_bank-project/notification-service:7f9655e #Ebuka add image path here
        ports:
        - name: http
          containerPort: 8003

        env:
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: rabbitmq-password
        - name: RABBITMQ_URL
          value: "amqp://minibank_broker:$(RABBITMQ_PASSWORD)@rabbitmq.minibank.svc.cluster.local:5672/"
        - name: APP_PORT
          value: "8003"

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop: ["ALL"]

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi

        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 10

        volumeMounts:
        - name: config-volume
          mountPath: /etc/minibank/config
          readOnly: true
        - name: secret-volume
          mountPath: /etc/minibank/secrets
          readOnly: true

      volumes:
      - name: config-volume
        configMap:
          name: notification-config
      - name: secret-volume
        secret:
          secretName: notification-secret