apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: minibank
automountServiceAccountToken: false
imagePullSecrets:
- name: ghcr-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iam-sa
  namespace: minibank
automountServiceAccountToken: false
imagePullSecrets:
- name: ghcr-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wallet-ledger-sa
  namespace: minibank
automountServiceAccountToken: false
imagePullSecrets:
- name: ghcr-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-sa
  namespace: minibank
automountServiceAccountToken: false
imagePullSecrets:
- name: ghcr-secret