apiVersion: v1
kind: Service
metadata:
  name: wallet-ledger-service
  namespace: minibank
  labels:
    app: wallet-ledger-service
spec:
  type: ClusterIP
  selector:
    app: wallet-ledger-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
